version: '3.4'

services:
  sampedapr.api:
    image: ${DOCKER_REGISTRY-}sampedaprapi
    build:
      context: .
      dockerfile: SampeDapr.Api/Dockerfile

  sampedapr.api-dapr:
    image: "daprio/daprd:latest"
    command: [ 
        "./daprd", 
        "-app-id", "sampe-dapr-api", 
        "-app-port", "80",
        "--placement-host-address", "placement:50006",
        "--resources-path", "./components"
    ]
    volumes:
        - "./DaprComponents/:/components"
    depends_on:
        - placement
        - sampedapr.api
    network_mode: "service:sampedapr.api"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
